### ISSUE TITLE
Scheduling Blockout U/X

### ISSUE THREAD

**Issue by sarahwicks** [fosterful/scheduler#172]
User Story:

As a Volunteer, I need a a more intuitive U/X in the scheduling app so that I can set recurring blockout times easily.

Acceptance Criteria:

Please consider these enhancements to the recurring blockout date feature:

- [ ] Every weekday
- [ ] Every [Monday/Tuesday/Weds/etc.]
- [ ] Every other [Monday/Tuesday/Weds/etc.]
- [ ] The [first/second/third/fourth] [M/Tu/W] of the month
etc.

**Comment by benjaminwood** [comment]
Related: #171

@sarahwicks do you have any apps/services which have recurring scheduling UI/UX that you like? As I mentioned in #171, the current UI is very flexible but that also makes it less intuitive. I think the solution is to implement something less flexible/power, but easier to understand.
