### ISSUE TITLE
VC/RM Leader Dashboard

### ISSUE THREAD

**Issue by sarahwicks** [fosterful/scheduler#174]
User Story:

As a Volunteer Coordinator/Regional Manager, I need a dashboard so that I can check stats related to my site.

Minimum Acceptance Criteria:

- [x] View # of requests for a specified time period (week/month/year)
- [x] View # of total volunteer hours served for a specific time period for the office
- [x] View # of filled and unfilled requests for a specific time period
- [x] View most active volunteers by # of hours served in a specific time period
- [x] View most active social workers by # of requests made in a specific time period
  * Most active users by number of needs made in a specific time period (+ indicate what kind of user VC/SW)

**Comment by creaturenex** [comment]
![Screenshot from 2022-06-13 18-45-50](https://user-images.githubusercontent.com/15052690/173459838-51956ccc-c6b2-46b8-a8f2-ede17c231bc5.png)

**Comment by creaturenex** [comment]
Issue to solve pertaining this feature
- Date Picker
  - [ ] Flash warning please enter dates when pressing save to prevent error when saving
  - [ ] change button to submit
  - [ ] Fix date box to look available, currently greyed out but it works
- Tables
  - [ ] Group by roles then sort

**Comment by creaturenex** [comment]
![Screenshot from 2022-06-16 12-13-44](https://user-images.githubusercontent.com/15052690/174117326-d19ff7f2-6950-4699-b7d9-1d2145936422.png)

**Comment by creaturenex** [comment]
See this issue regarding grey background for flatpickr.
[grey input field](https://github.com/flatpickr/flatpickr/issues/1456)

**Comment by creaturenex** [comment]
Test for
- [ ] Service::DashboardQuery Object
- [ ] Dashboard Controller - new test
- [ ] Form View
- [ ] Form Controller possible

**Comment by creaturenex** [comment]
Based on last discussion, view should be handled in card format.
![Screenshot from 2022-06-28 16-58-34](https://user-images.githubusercontent.com/15052690/176286733-15591636-7f2c-4f36-95f1-6054582cf971.png)

**Comment by creaturenex** [comment]
Issue resolved by PR #835
