### ISSUE TITLE
Change "Preferred Culture" to "Preferred Race/Ethnicity"

### ISSUE THREAD

**Issue by sarahwicks** [fosterful/scheduler#179]
The only two ethnicities recognized by the US govt are "Hispanic" and "non-Hispanic." The other entries are races, not cultures. Suggest alignment with US census terminology and values to avoid sensitivity issues.

Races:
- White
- Black or African American
- American Indian or Alaska Native
- Asian
- Native Hawaiian or Other Pacific Islander

Ethnicities:
- Hispanic (y/n)

https://www.census.gov/mso/www/training/pdf/race-ethnicity-onepager.pdf

Acceptance Criteria:

- [ ] Volunteers can select both a race and an ethnicity in the "profile" section of the scheduler
- [ ] Social workers can select from the same race and ethnicity lists when creating a need

**Comment by benjaminwood** [comment]
@sarahwicks can you provide a mapping for existing users from the current options to the new options?

**Comment by creaturenex** [comment]
On backlog to determine better verbage.
