### ISSUE TITLE
Age Difference Enforcement: Temporary Fix

### ISSUE THREAD

**Issue by sarahwicks** [fosterful/scheduler#209]
User Story:

As a child entering foster care, I need to be cared for by an Office Mom or Dad who is at least [TBD] years older than I am so that I feel comfortable and so that OMD avoids risk.

Dependencies:

- Full fix outlined in #178. This fix should be undone once #178 is complete.

Acceptance Criteria:

Temporary Fix: Please add this text to this profile field:

Current Text: Select one or more age ranges that you would like to work with

- [ ] New Text: Select one or more age ranges that you would like to work with. Do not select "13-17" unless you are at least [TBD] years old."

**Comment by sarahwicks** [comment]
@benjaminwood, added dev effort per your comment above, adjust as necessary

**Comment by mikearino** [comment]
@sarahwicks Have you decided how much older the person caring for a child between the age of 13-17 needs to be yet?
