### ISSUE TITLE
Multiple Users per Email Address

### ISSUE THREAD

**Issue by sarahwicks** [fosterful/scheduler#218]
**User Story:**

As a user who shares an email address with another volunteer, I need the app to recognize me as a unique user so that I can get unique shift notifications.

**Background:**

We have multiple sites that have volunteers who share an email address. 

**Acceptance Criteria:**

- [ ] Two volunteers who share an email address can set different schedule requirements

- [ ] Two volunteers who share an email address can enter different profile information (i.e., demographics, phone number, etc.)

- [ ] " " "....can receive separate shift notifications based on their availability

- [ ]

**Comment by sarahwicks** [comment]
@benjaminwood - Can you guys add your dev estimate to this? Or if this is a no-go for the app as it's currently designed, can you help us think of another way to solve this issue? We think multiple volunteers sharing an email is going to be a recurring use case, especially given the demographics of our volunteers.

**Comment by sarahwicks** [comment]
or @nvick ^

**Comment by nvick** [comment]
@sarahwicks the tool we use for authentication is built around a user having a unique email address. There are ways we could possibly work around it, but this will require some time to think through.
