### ISSUE TITLE
SPIKE: How to prevent system from double-counting kids

### ISSUE THREAD

**Issue by sarahwicks** [fosterful/scheduler#228]
If multiple shifts are created for the same kids, the app will count those kids uniquely when they should be counted once. This bloats our reporting. Likewise, if the same children are served over multiple days, they'll be counted each day. We need to figure out a way to link shifts to children without exposing their personal data.

**Comment by joelmichael** [comment]
The only way I can think to do this would be to create a new record representing the household that is served, which could then be re-used when creating new needs. As-is, there is no connection between needs and unique households.

**Comment by joelmichael** [comment]
Since we want it to be anonymous, I can't really think of a solution. The way to readily identify a household would be via some personal data, such as a name or street address.
