### ISSUE TITLE
Ability to request multiple volunteers for a shift

### ISSUE THREAD

**Issue by sarahwicks** [fosterful/scheduler#229]
User Story:

As a creator of a new need, I need to request the appropriate number of volunteers for a shift so that there are enough adults to meet the unique needs of the child(ren) in care. 

Acceptance Criteria:

- [ ] The request creation UI allows a social worker to specify how many volunteers are needed for that request.

- [ ] The "manage shifts" UI displays the name of each volunteer who has signed up for a given shift

- [ ] The top-level shift information shows volunteers how many volunteers are still needed for each hour in the need

- [ ] Reporting should convey multiple volunteers but not double-count the children.

- [ ] A volunteer would need to be able to remove him/herself from a shift without affecting other volunteers who have signed up for that shift

Relates to:
#187 
#228

**Comment by sarahwicks** [comment]
@nvick @benjaminwood @kyleboe Please estimate dev work, thanks!

**Comment by creaturenex** [comment]
@benjaminwood followup

**Comment by benjaminwood** [comment]
I'm going to go ahead and open a new issue for this with updated criteria
