### ISSUE TITLE
Refactor EditBlockoutModal update/delete handlers

### ISSUE THREAD

**Issue by benjaminwood** [fosterful/scheduler#39]
Here https://github.com/OfficeMomsandDads/scheduler/blob/f9ec56a199829488c3716711c7cbda4bf54abe91/app/javascript/components/blockouts/EditBlockoutModal/index.js#L104

And here
https://github.com/OfficeMomsandDads/scheduler/blob/f9ec56a199829488c3716711c7cbda4bf54abe91/app/javascript/components/blockouts/EditBlockoutModal/index.js#L55

Both of these functions are huge and packed with complexity that is begging to be refactored but we have to move on to other things now.

**Comment by sarahwicks** [comment]
Please add a non-dev description of this issue so we can groom it. Thanks! @benjaminwood @nvick

**Comment by benjaminwood** [comment]
I'm going to close this. It's not a high-value target because the code literally has not been touched since it was implemented.
