### ISSUE TITLE
Bug in sidekiq-cron configuration

### ISSUE THREAD

**Issue by benjaminwood** [fosterful/scheduler#806]
Post-shift survey emails are not being sent (implemented in #718).

Upon review, I found an error in our sidekiq cron configuration:

https://github.com/fosterful/scheduler/blob/abc31a7903ef659ab628f74da68a008a8c9d0af9/config/initializers/sidekiq.rb#L12-L24

I believe the (incorrect) assumption was that `Sidekiq::Cron::Job.find` would return `nil` if a matching cron job is not found. This is not the case, and instead, an empty `Sidekiq::Cron::Job` object is returned, but the value is truthy, so the condition skips the installation of the cron job.

We should follow the usage instructions in the readme. There are a couple ways to handle it, but I'd vote that we use the `Sidekiq::Cron::Job.load_from_array!` method (note the bang `!`). You can read up on this in the readme:

https://github.com/ondrejbartas/sidekiq-cron/blob/c91d0f22f95cb3a297c06e2c15494d95c8085f28/README.md?plain=1#L166-L209

**Comment by creaturenex** [comment]
Are only the shift survey being impacted or are the Reminders crons also impacted? Looks like the same logic is applied.

**Comment by benjaminwood** [comment]
Yeah, I believe both would be impacted by this misconfiguration but for some reason (perhaps manual intervention) the reminders cron is installed/working in production. Let's change both to use `load_from_array!`, though.
