### ISSUE TITLE
Fix date range picker end date from flexing below start, preventing view.

### ISSUE THREAD

**Issue by creaturenex** [fosterful/scheduler#832]
![Screenshot from 2022-06-13 16-32-05](https://user-images.githubusercontent.com/15052690/173440186-b6c4c2a5-7134-4298-ad80-19684bd54475.png)

**Comment by creaturenex** [comment]
Hello! Awesome, this is happening in the dashboard/reports.html.haml view. Specifically the react component. Please let me know if you have any questions.

**Comment by creaturenex** [comment]
Hmm are you using vscode by any chance? I know vscode can build/run the container within, but it requires docker to have sudo privileges. Haven't really tried it without it so not sure what can cause the issue besides a misconfiguration. Let me see if I can find you some help. @benjaminwood @nvick Any ideas?

**Comment by nvick** [comment]
Hey @cidsinga! Have you pulled the latest version of master? If so, I would do `docker-compose down`, open the VSCode Command Palette, and run Reopen in Container. If that doesn't work, I'd be glad to pair up for a few to get it going.

**Comment by cidsinga** [comment]
@nvick Heyo! I have pulled from master. I was attempting to run my container from iTerm.  I've pruned and tried starting fresh. I'll see if I have any more success or hints by doing it in VSCode. I'll try that shortly, and hit you up for a pair if I'm without success. It'd be great just to say hi regardless!

**Comment by creaturenex** [comment]
Thanks @nvick

**Comment by nvick** [comment]
For sure!

**Comment by nvick** [comment]
@cidsinga shoot me an email with some times that would work for you.

**Comment by creaturenex** [comment]
Issue resolved by PR #838 and merged. Thanks for the help @cidsinga. Hope to see you around more often :)
